Repository FromDoppler/doppler-integrations-mfe, pull requests merged in 2023-12, with the labels that each got.

#19 DOI-1142 Add campaign table
  src/components/AssistedShopping/AreaChart/AreaChart.js
  src/components/AssistedShopping/Table/Table.js
  src/components/AssistedShopping/index.js
Labels: size/L

#28 [DOI-1143] Add Donut chart to dashboard
  src/components/AssistedShopping/DonutChart/DonutChart.js
  src/components/AssistedShopping/index.js
  src/components/i18n/en.tsx
  src/components/i18n/es.tsx
  src/components/shared/Dropdown/Dropdown.js
Labels: size/M

#31 [DOI-1152] Add bar chart for assisted Shopping dashboard
  src/components/AssistedShopping/BarChart/BarChart.js
  src/components/AssistedShopping/DonutChart/DonutChart.js
  src/components/AssistedShopping/index.js
Labels: size/L

#32 [DOI-1154] Add second donut chart to assisted shopping dashboard
  src/components/AssistedShopping/index.js
  src/components/i18n/en.tsx
  src/components/i18n/es.tsx
Labels: size/S

#36 [DOI-1153] Modify KPI component to use new design
  src/components/AssistedShopping/index.js
  src/components/i18n/en.tsx
  src/components/i18n/es.tsx
  src/components/shared/kpi/Kpi.js
  src/components/shared/kpi/Kpi.test.js
Labels: size/L

#37 fix: fix in layout and add footer
  src/components/AssistedShopping/AreaChart/AreaChart.js
  src/components/AssistedShopping/BarChart/BarChart.js
  src/components/AssistedShopping/DonutChart/DonutChart.js
  src/components/AssistedShopping/Table/Table.js
  src/components/AssistedShopping/index.js
  src/components/shared/Dropdown/Dropdown.js
Labels: size/L

#38 [DOI-1162] Add footer component
  src/components/AssistedShopping/index.js
  src/components/i18n/en.tsx
  src/components/i18n/es.tsx
  src/components/shared/Footer/footer.js
Labels: size/M

#39 fix: fix in table layout assisted sales
  src/components/AssistedShopping/Table/Table.js
  src/components/AssistedShopping/index.js
Labels: size/L

#40 [DOI-1163] Add translations
  src/components/AssistedShopping/AreaChart/AreaChart.js
  src/components/AssistedShopping/BarChart/BarChart.js
  src/components/AssistedShopping/DonutChart/DonutChart.js
  src/components/AssistedShopping/Table/Table.js
  src/components/AssistedShopping/index.js
  src/components/i18n/en.tsx
  src/components/i18n/es.tsx
  src/components/shared/Dropdown/Dropdown.js
  src/components/shared/Footer/footer.js
Labels: size/L

#44 [DOI-1155] Add integrations API client
  public/index.html
  src/abstractions/application/AppConfiguration.ts
  src/abstractions/application/AppServices.ts
  src/abstractions/integrations-api-client.ts
  src/composition-root.ts
  src/default-configuration.ts
  src/implementations/SingletonLazyAppServicesContainer.ts
  src/implementations/dummies/integrations-api-client.tsx
  src/implementations/dummies/sample-assisted-sales.json
  src/implementations/dummies/sample-third-party-connections.json
  src/implementations/integrations-api/IntegrationsApiClientImpl.test.ts
  src/implementations/integrations-api/IntegrationsApiClientImpl.ts
Labels: size/XL
